# Generated by Django 2.2.7 on 2019-11-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_name', models.CharField(max_length=100)),
                ('stall_type', models.CharField(choices=[('Book', 'Book'), ('Food', 'Food')], default='Type N/A', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('stall_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('book_genre', models.CharField(choices=[('SCIFI', 'SCI-FI'), ('ACTION', 'ACTION'), ('HORROR', 'HORROR'), ('ROMANTIC', 'ROMANTIC'), ('NONFICTION', 'NONFICTION'), ('FICTION', 'FICTION'), ('CLASSIC', 'CLASSIC'), ('POETRY', 'POETRY'), ('THRILLER', 'THRILLER'), ('MYSTERY', 'MYSTERY'), ('CHILDREN', 'CHILDREN')], default='Type N/A', max_length=10)),
                ('release_date', models.DateField()),
                ('stalls', models.ManyToManyField(to='boimelawebApp.Stall')),
            ],
            options={
                'ordering': ('book_name',),
            },
        ),
    ]
